stages:
  - check
  - deploy
  - registry
  - update-releases

prettier:
  stage: check
  image: node:24
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@latest-11 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - pnpm format --check
    - pnpm lint

pages:
  stage: deploy
  image: node:24
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@latest-11 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
  artifacts:
    paths:
      - dist
  publish: dist
  variables:
    BASE_URL: "/calyxos-webinstall"
  only:
    - main

build:
  image: docker:28
  stage: registry
  services:
    - name: docker:28-dind
      alias: docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

releases:
  image: node:24
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - corepack prepare pnpm@latest-11 --activate
    - pnpm config set store-dir .pnpm-store
  stage: update-releases
  script:
    - pnpm update-releases
    - git diff src/releases.json
  artifacts:
    paths:
      - public/releases/index.json
