image: node:lts

pages:
  stage: deploy
  before_script:
    - npm install
    - npm install git+https://review.calyxos.org/CalyxOS/fastboot.js
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  publish: dist
  variables:
    BASE_URL: '/calyxos-webinstall'
  only:
    - main
