stages:
  - check
  - deploy
  - registry
  - update-releases

prettier:
  stage: check
  image: node:lts
  before_script:
    - npm ci
  script:
    - npx prettier --check .
    - npx eslint

pages:
  stage: deploy
  image: node:lts
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  publish: dist
  variables:
    BASE_URL: "/calyxos-webinstall"
  only:
    - main

build:
  image: docker:27
  stage: registry
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

releases:
  image: node:lts
  before_script:
    - npm ci
  stage: update-releases
  script:
    - npm run update-releases
    - git diff public/releases/index.json
  artifacts:
    paths:
      - public/releases/index.json
