image: node:lts

pages:
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  publish: dist
  environment:
    BASE_URL: '/calyxos-webinstall'
  only:
    - main
