export const IMAGES = [
  {
    nickname: "boot",
    img_name: "boot.img",
    sig_name: "boot.sig",
    part_name: "boot",
    optional: false,
    type: "BootCritical",
  },
  {
    nickname: "bootloader",
    img_name: "bootloader.img",
    sig_name: "",
    part_name: "bootloader",
    optional: true,
    type: "Extra",
  },
  {
    nickname: "init_boot",
    img_name: "init_boot.img",
    sig_name: "init_boot.sig",
    part_name: "init_boot",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "",
    img_name: "boot_other.img",
    sig_name: "boot.sig",
    part_name: "boot",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "cache",
    img_name: "cache.img",
    sig_name: "cache.sig",
    part_name: "cache",
    optional: true,
    type: "Extra",
  },
  {
    nickname: "dtbo",
    img_name: "dtbo.img",
    sig_name: "dtbo.sig",
    part_name: "dtbo",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "dts",
    img_name: "dt.img",
    sig_name: "dt.sig",
    part_name: "dts",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "odm",
    img_name: "odm.img",
    sig_name: "odm.sig",
    part_name: "odm",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "odm_dlkm",
    img_name: "odm_dlkm.img",
    sig_name: "odm_dlkm.sig",
    part_name: "odm_dlkm",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "product",
    img_name: "product.img",
    sig_name: "product.sig",
    part_name: "product",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "pvmfw",
    img_name: "pvmfw.img",
    sig_name: "pvmfw.sig",
    part_name: "pvmfw",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "radio",
    img_name: "radio.img",
    sig_name: "",
    part_name: "radio",
    optional: true,
    type: "Extra",
  },
  {
    nickname: "recovery",
    img_name: "recovery.img",
    sig_name: "recovery.sig",
    part_name: "recovery",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "super",
    img_name: "super.img",
    sig_name: "super.sig",
    part_name: "super",
    optional: true,
    type: "Extra",
  },
  {
    nickname: "system",
    img_name: "system.img",
    sig_name: "system.sig",
    part_name: "system",
    optional: false,
    type: "Normal",
  },
  {
    nickname: "system_dlkm",
    img_name: "system_dlkm.img",
    sig_name: "system_dlkm.sig",
    part_name: "system_dlkm",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "system_ext",
    img_name: "system_ext.img",
    sig_name: "system_ext.sig",
    part_name: "system_ext",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "",
    img_name: "system_other.img",
    sig_name: "system.sig",
    part_name: "system",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "userdata",
    img_name: "userdata.img",
    sig_name: "userdata.sig",
    part_name: "userdata",
    optional: true,
    type: "Extra",
  },
  {
    nickname: "vbmeta",
    img_name: "vbmeta.img",
    sig_name: "vbmeta.sig",
    part_name: "vbmeta",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "vbmeta_system",
    img_name: "vbmeta_system.img",
    sig_name: "vbmeta_system.sig",
    part_name: "vbmeta_system",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "vbmeta_vendor",
    img_name: "vbmeta_vendor.img",
    sig_name: "vbmeta_vendor.sig",
    part_name: "vbmeta_vendor",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "vendor",
    img_name: "vendor.img",
    sig_name: "vendor.sig",
    part_name: "vendor",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "vendor_boot",
    img_name: "vendor_boot.img",
    sig_name: "vendor_boot.sig",
    part_name: "vendor_boot",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "vendor_dlkm",
    img_name: "vendor_dlkm.img",
    sig_name: "vendor_dlkm.sig",
    part_name: "vendor_dlkm",
    optional: true,
    type: "Normal",
  },
  {
    nickname: "vendor_kernel_boot",
    img_name: "vendor_kernel_boot.img",
    sig_name: "vendor_kernel_boot.sig",
    part_name: "vendor_kernel_boot",
    optional: true,
    type: "BootCritical",
  },
  {
    nickname: "",
    img_name: "vendor_other.img",
    sig_name: "vendor.sig",
    part_name: "vendor",
    optional: true,
    type: "Normal",
  },
]
